### ISSUE TITLE
Comments on apply_explicit

### ISSUE THREAD

**Issue by dlg0** [project-asgard/asgard#141]
https://github.com/project-asgard/asgard/blob/7bedea70a8d57796a2058e65ac5ad1c0e6ef8082/src/time_advance.cpp#L88

In trying to interpret what's happening here I have the following comments ...

1. I'd suggest that `apply_explicit` should be named `apply_A`. Nominally it is not associated with either explicit or implicit time advance, but rather just applying the system matrix to the present solution vector. 
2. The naming and comments surrounding `copy_chunk_inputs` and `copy_chunck_ouputs` could be more descriptive, i.e., at present, it does not tell me what those inputs and outputs are. i.e., are they pieces of the input and output vectors, or are they the coefficient matrices, or what? 
3. Could `copy_chunk_inputs` and `copy_chunk_ouputs` be a single function with the order of the arguments reversed for the second call? Or at least have the source/destination argument order be the same in both calls?

**Comment by grahamlopez** [comment]
RE 1) I can see your argument for how `apply_explicit` is not the best name. However, I would then ask - and not just to be pedantic; I really don't know - what is "A"?

RE 3) I thought the same thing when I was reviewing the code; similar to mirroring `cudaMemCpy`. But I decided to leave it be since a) the implementations are different enough that we would essentially have two completely separate functions under a single name, b) I couldn't convince myself that this would be easier to understand in then end. `cudaMemCpy` has a tag argument that says which way the copy goes; we could add similar, but then we're just moving the `xxx` from `copy_chunk_xxx` to its parameters. Since you have brought it up and I was initially on the fence about it, we can discuss further.

**Comment by bmcdanie** [comment]
during the issuethon, I plan to address some of this - maybe `apply_system`? `apply_system_matrix`? 

hoping that those `copy` functions will be removed when #166 is addressed, but if they aren't, I will address the naming.
