### ISSUE TITLE
PDE Spec 2.0

### ISSUE THREAD

**Issue by dlg0** [project-asgard/asgard#150]
- [ ] Single place where a new PDE needs to be added. 
- [ ]

**Comment by stonecoldhughes** [comment]
command line pde string ---> asgard pde scoped enum type ---> select precompiled PDE to use.
With this current workflow, I can't think of any way to reduce the number of places we have to add a PDE. However, what if we did not precompile all the PDEs? What if, instead, we compile Asgard with only the PDE base class. On the command line, we pass the path of a ".so" file that contains only the derived class PDE we want to use. In Asgard, we can programmatically load the derived class and use it. Some advantages to this approach are that Asgard is not required to carry around every possible derived class option of "PDE". It would be more flexible because any class that implements all of pde_base's virtual functions could be passed in and used. How could we validate the derived class passed in this way? Simply check for the existence of all virtual functions in the .so file and possibly even run them to make sure they don't segfault. Perhaps this could be an option for how to run a PDE that we have not validated and compiled into Asgard ourselves. It is less safe, but more flexible for situations in which flexibility is more appealing than safety.

**Comment by dlg0** [comment]
Thanks for thinking about this. As you point out, the single place for new PDEs aspect of this issue is likely something that may go away once we settle on a new approach to the PDE spec. But I think the place to start with this refactor is to document all the things that are wrong with the present PDE spec implementation. One such problem is that of the single place to add a new PDE, so I'd suggest we expand the list above as we remember what the problems are. _Then_ we consider alternative approaches that might address those.  Some notes ...

- This falls into the `pde refactor` class of issues so isn't part of IssueThon19.
- I don't think I'd like to be passing a path on the command line.
- An invalid PDE should not compile.

**Comment by mkstoyanov** [comment]
Stale issue, open a new one, if still relevant.
