### ISSUE TITLE
ensure fortran for openblas

### ISSUE THREAD

**Issue by grahamlopez** [project-asgard/asgard#204]
when our cmake builds openblas for the user, there must be a fortran compiler present. Otherwise, some blas symbols are not present and linking asgard components fails later on.

we need to ask openblas to ensure that it builds all of blas or else fail/stop. as an inferior second choice, we can check for the availability of a fortran compiler before attempting to build openblas.

**Comment by stonecoldhughes** [comment]
My best idea so far is to set an OpenBlas specific CMake variable to the function call that builds OpenBlas. I think the variable "ONLY_CBLAS" should be set to 0. I have not tried this yet.

**Comment by stonecoldhughes** [comment]
Also, could someone please explain the inferiority of the "inferior second choice" approach?

**Comment by grahamlopez** [comment]
If there is not a user-facing way already built in to openblas to make this request, we should not try to go hacking it in.

The second way is slightly inferior because it only protects against the special case of the blas symbols not being built due to a lack of fortran compiler, but does not protect against the more general possibility of the blas symbols not being built due to some other reason.

**Comment by bmcdanie** [comment]
The second choice is also inferior because it is farther from the condition we are checking for.

the condition we want to check for is whether or not blas is built with the correct symbols.

close to this condition is openblas _is able to find_ a fortran compiler.

farther from this condition is _we found_ a fortran compiler.

you can see how the last two are different and could perpetuate what we're trying to fix - a silent error. we could be searching for the compiler in a different way than openblas is.

**Comment by grahamlopez** [comment]
True nuff! Well said, @bcmdanie

**Comment by stonecoldhughes** [comment]
Please check #211 as a fix for this issue.

**Comment by bmcdanie** [comment]
closed by #211 .
