### ISSUE TITLE
investigate alternative options for the kron-mult

### ISSUE THREAD

**Issue by dlg0** [project-asgard/asgard#234]
Being the core kernel, alternative options to maximize performance should be investigated. The options to investigate we have identified so far are ...

- N^4 + shared memory with no storage approach (likely good for small `deg*deg` mats)
- CUDA batched 6D kron-mult (The C code @efdazedo  wrote)
- Work element-wise versus dimension-wise
- Fixed strided GEMM (copy or nocopy)
- Custom kernel with blas at the threadblock level via `cublas_dx` (not available yet)
- Build batches on the GPU (kokkos ordered map?)  

@grahamlopez @efdazedo @bmcdanie @stonecoldhughes

**Comment by bmcdanie** [comment]
From @efdazedo:

There is a compromise algorithm of using nested loops with a block size "nb" and in the inner most loop, perform kron product using temporary storage "BX".

Here is a simple matlab code to illustrate the idea.  The "BX" array may be nb by nb shared memory.

Instead of O(N^4) work, the nested loop  will perform  (N/nb)^4 * (2 * nb^3)  or   N^4 * (2/nb)  operations. So there is reduction by factor of (2/nb). The extreme case is nb == N, then we are back to the O(2N^3) algorithm.

Perhaps depending on the shapes and sizes of the matrices, this may be a reasonable compromise. It does not need extra temporary storage in global device memory, just shared memory inside the thread block.  

If OpenMP target offload does not allow shared memory, at least it will give a fixed bound on the amount of temporary storage needed.  Maybe the L1 and L2 cache on GPU will still do a reasonable job of reducing data movement between global device memory and cache.

Ed

**Comment by bmcdanie** [comment]
We have investigated or implemented all of the above - building batches on GPU (#288), working elementwise with batched 6D kronmult w/ custom kernel (#275). also, I looked into fixed strided GEMM but couldn't get the coefficient layout to work with that approach.
