### ISSUE TITLE
Change upwind to downwind and vice versa in PDE file spec

### ISSUE THREAD

**Issue by stefan-schnake** [project-asgard/asgard#449]
**Describe the bug**
Upwind needs to be changed to downwind and vice versa in PDE file and src/pde/pde_base.hpp

**Comment by stefan-schnake** [comment]
Also needs to be changed for all PDEs

**Comment by ckendrick** [comment]
@stefan-schnake I was looking at old issues and came across this. This may have been done in #414 as it updated every PDE and made a lot of grad->div changes? Also this was added to the `partial_term` class based on the Matlab implementation which inverts the winding direction for grad coeffs:
https://github.com/ckendrick/asgard/blob/f580dae1960355c2f7e3319162c1034fae67b68a/src/pde/pde_base.hpp#L255-L285

Since this was opened after the above PR was merged, we should double-check that this still needed.

**Comment by mkstoyanov** [comment]
Done in #706
