### ISSUE TITLE
Allow CLI to set  the number of GMRES iterations and tolerance

### ISSUE THREAD

**Issue by mkstoyanov** [project-asgard/asgard#484]
Comes after #482

Currently we implement the restarted GMRES, but number of inner and outer iterations is hardcoded to the size of the matrix, i.e., the method never restarts. As the size of the GMRES basis increases, the cost of manipulating the basis grows and dominates over the cost of the matrix-vector product.

Similarly, the tolerance is hard-coded and does not take into account the size of the mesh. Note that the discrete l-2 norm converges to the continuous l-2, but only if we scale by 1/sqrt(N), and that is for a function discretized in 1D over a uniform mesh. The true relation can be quite complex, hence we need a CLI switch to adjust the tolerance on a case-by-case basis and allow the user to set the tolerance based on mesh size of needs for the specific application.

**Comment by stefan-schnake** [comment]
Since the GMRES solve is taking place in the wavelet space, there should be no scaling needed.  The wavelet functions are orthonormal in L^2 such that (if the coordinates are cartesian) the discrete 2-norm coincides with the continuous L^2 norm.  I believe real space error is calculated from the quadrature data which does need a scaling since the values are O(1),  I believe the code currently uses RMSE.

**Comment by mkstoyanov** [comment]
Given how the wavelet support goes to zero, scaling the basis seems messy. I find this unsettling and I need to think more on it. Thanks for point it out.

Regardless, the feature about adjusting the tolerance trough the CLI is still needed, not every problem will use the same tolerance.
